# model.py
import torch
import torch.nn as nn


class ImitationModel(nn.Module):
    def __init__(self):
        super().__init__()

        # CNN backbone: treats the 9x9 sudoku board as a single-channel image
        # Each conv layer captures local constraints (rows, columns, 3x3 boxes)
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.ReLU(),
        )
        # Predict which of the 81 cells to fill next
        self.cell_head = nn.Linear(128 * 81, 81)
        # Predict which digit (1-9) to place in the selected cell
        self.num_head  = nn.Linear(128, 9)

    def forward(self, x, cell_label=None):
        """
        Processes the input Sudoku board and predicts the next cell to fill and the digit to place.

        This method uses a CNN-based approach to analyze the board, followed by a
        classification mechanism to identify the next cell and the digit for the cell.

        Parameters:
        x (Tensor): A tensor of shape (batch, 81) representing the flattened Sudoku board,
        where 0 represents an empty cell and values from 1-9 are filled numbers.
        cell_label (Optional[Tensor]): A tensor containing the indices of the cells to be
        considered. If provided, it overrides the cell prediction generated by the model.

        Returns:
        Tuple[Tensor, Tensor]: A tuple where:
        - The first tensor contains logits predicting the next cell to fill for each
        board in the batch.
        - The second tensor contains logits predicting the digit (1-9) to be placed
        in the selected cell, for each board in the batch.
        """
        # x: (batch, 81) - flattened sudoku board (0 = empty, 1-9 = filled)
        x_2d = x.view(-1, 1, 9, 9) # reshape to image format: (batch, 1, 9, 9)
        feat = self.cnn(x_2d) # extract spatial features: (batch, 128, 9, 9)
        feat = feat.view(x.size(0), 128, 81) # flatten spatial dims: (batch, 128, 81)
        cell_logits = self.cell_head(feat.view(x.size(0), -1))

        if cell_label is not None:
            idx = cell_label
        else:
            idx = cell_logits.argmax(dim=1)

        # Predict which of the 81 cells to fill next
        cell_feat = feat[torch.arange(feat.size(0)), :, idx]
        # Predict which digit (1-9) to place in the selected cell
        num_logits = self.num_head(cell_feat)

        return cell_logits, num_logits